name: radio_app
description: "A New Radio App"
publish_to: 'none'
version: 1.0.2

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get:
  http:
  audioplayers: ^6.1.0
  flutter_volume_controller: ^1.3.2
  awesome_notifications: ^0.9.3+1
  cached_network_image:
  internet_connection_checker: ^1.0.0+1
  permission_handler:
  xml:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.7

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/AppLogo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/AppLogo.png"